language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install termcolor
  - pip install coverall
# command to run tests
script:
  - python3 -m unittest
  - coverage run test_rpn.py 

