language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install termcolor
# command to run tests
script:
  - python3 -m unittest

  # single test suite, non-parallel build.

script: "sbt clean coverage test"

after_success: "sbt coveralls"
